### PR TITLE
Alternative way of pulling parents with .parentNode

### PR DESCRIPTION
**Pull request by bevacqua**
Non-breaking fix to #251

### CODE REVIEW

**Comment by jimf** [comment]
:+1: Nice.

**Comment by bevacqua** [comment]
Could you test this on your `<svg>` example and see if it fixes the issue?

**Comment by jimf** [comment]
Just got in the car, but I can give it a shot later tonight.

**Comment by jimf** [comment]
@bevacqua confirmed this works.

**Comment by bevacqua** [comment]
Deployed into `3.5.4`

**Pull request closed without merging**
