### PR TITLE
Automaticaly detect direction (vertical/horizontal) if not set

### PR DESCRIPTION
**Pull request by luckylooke**
algorithm based on comparing widths and heights of parent and first child

If parent height is more similar to child height then their width, then direction is horizontal.

### CODE REVIEW

**Comment by luckylooke** [comment]
There are some changes in files comparison I didnt made, I was editing only function getReference! Could be other changes made by build process? I have ran command:
```
npm run build
```

**Comment by bevacqua** [comment]
YAGNI

**Comment by luckylooke** [comment]
Im using it ;)

**Comment by bevacqua** [comment]
Thanks but I'll pass

**Pull request closed without merging**
