### PR TITLE
No delay clicks

### PR DESCRIPTION
**Pull request by bevacqua**
This thing fixes the necessity for `delay` option, which was obnoxiously bad design. Initially suggested in #147 by @lkrids

### CODE REVIEW

**Comment by lkrids** [comment]
In most browsers the user can drag a link into the address bar, favorites bar, etc.  The default drag operation for ```<a>``` is still happening when trying to drag an item by clicking a child ```<a>```.

**Comment by bevacqua** [comment]
Yes that's intentional. You could use invalid to prevent anchors from being dragged

**Comment by lkrids** [comment]
How do you drag an element (orange, blue, or green) if the mousedown event starts on a ```<a>``` (purple)?

http://jsbin.com/xaporaxowi/1/edit?html,output

**Comment by bevacqua** [comment]
You don't have to do anything special

**Comment by bevacqua** [comment]
Try it now. Works fine for me

**Comment by lkrids** [comment]
me too, thanks!  It's been fun collaborating on this.

**Comment by bevacqua** [comment]
:rocket:

**Pull request merged**
