### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by bevacqua** [comment]
Thanks, but that doesn't say they won't be relying in the field in the future, so I'll just leave it in for now.

**Comment by kkirsche** [comment]
To each their own. From every discussion I've had with the teams it sounds as though bower will be dying a slow and painful death as the push will be for NPM in the future. The goal of version was for use in a package manager application which was never developed and instead was made for NPM. Best of luck, but I'd expect to see it unused forever...

**Comment by bevacqua** [comment]
Oh yeah, I agree completely, I just support bower so people don't occasionally post issues asking for a bower registration. I should probably stop supporting bower altogether in my future projects

**Comment by kkirsche** [comment]
That's reasonable. I can certainly understand that reason :+1: .

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Pull request closed without merging**
