### PR TITLE
handle container cursor

### PR DESCRIPTION
**Pull request by sethmcleod**
Style fix for #169

### CODE REVIEW

**Comment by bevacqua** [comment]
Cool but please just unroll the selector

**Comment by sethmcleod** [comment]
Sure, but what exactly do you mean by that? Targeting the ids directly?
```
#left-lovehandles > div, #right-lovehandles > div {
  cursor: initial;
}
```

**Comment by bevacqua** [comment]
Yup. Thanks

**Comment by sethmcleod** [comment]
This is ready for merge

**Comment by bevacqua** [comment]
please squash the commits

**Pull request merged**
