### PR TITLE
Option to use CSS3 translate(x,y) when dragging

### PR DESCRIPTION
**Pull request by romainbessugesmeusy**
By working on rendering issues on my app, I noticed Dragula was setting CSS top and left properties while dragging. I learned somewhere on the Internet that using CSS3 transform property is a great replacement for modern browsers, as it rely on animation frames and use the graphic card intensively. 

I added an option named "useTransform" that defaults to false, to prevent side-effects. If set to true, the top / left properties are set to 0, 0 when the _mirror is created, then the transform (and vendor transforms) are updated. 

I decided not to do additional check around the browser compatibilty because it is a dragula option, that would better be set accordingly. I tested the script on the latest Chrome, Safari and Firefox.
I also added a utility to set a vendor-prefixed style property in JS, maybe should I stick to the "transform" I'm dealing with...

Oh, and by the way it runs very, very smooth when turned on

### CODE REVIEW

**Comment by romainbessugesmeusy** [comment]
WHOA I think I messed a with the pull request somewhere... I see lots of changes even if I edited only 10 lines... gotta check my fork

**Comment by bevacqua** [comment]
I would gladly use it where able but

- Feature detection, option for this is pointless http://stackoverflow.com/questions/5661671/detecting-transform-translate3d-support
- Rebase instead of including code that's not part of the pull request
- Follow contribution guidelines, don't check in `dist`

**Comment by romainbessugesmeusy** [comment]
OK, I'll do this today !

**Comment by romainbessugesmeusy** [comment]
https://github.com/zamiang/detect-css3-3d-transform
What do you think of their idea of checking the useragent instead of the style properties ? Looks more reliable after all.

**Comment by bevacqua** [comment]
No. That's a terrible idea. Never rely on user agent

**Comment by romainbessugesmeusy** [comment]
Hey, I'm not sure if you get notified by my last commits, but I implemented the feature detection as you suggested

**Comment by romainbessugesmeusy** [comment]
Hey, any news ?

**Pull request closed without merging**
