### PR TITLE
fix(getCoord): on touchend, uses e.changedTouches instead of e.targetTouches, fixes #34

### LINKED ISSUE #34: On iOS 8, removeOnSpill is always triggered
When I re-order any element of the 3rd demo ( removeOnSpill ), on Safari 8 and Chrome, the element is removed. 
It's correctly re-ordered on desktop Chrome.

dragula

( iPhone 6, iOS 8.1.2 ).

The project is impressive tho ; )

### PR DESCRIPTION
**Pull request by marg51**
should fix #34

It works now on IOS 8, I can't test on iPad or android devices.

### CODE REVIEW

**Comment by bevacqua** [comment]
Could you make this multi-line?

**Comment by marg51** [comment]
is it better ?

**Comment by bevacqua** [comment]
yes. thanks!

**Comment by bevacqua** [comment]
`1.5.1`

**Pull request merged**
