### PR TITLE
Scroll while dragging

### PR DESCRIPTION
**Pull request by btecu**
This is @zeeamber's work. See https://github.com/bevacqua/dragula/pull/129. I've just merged his branch with master, since it seemed he has having troubles with it.

### CODE REVIEW

**Comment by zeeamber** [comment]
thanks @btecu

**Comment by bevacqua** [comment]
Please squash the commits. Thanks for fixing merge conflicts

**Comment by btecu** [comment]
Done.

**Comment by bevacqua** [comment]
Please fix issues in Travis over here https://travis-ci.org/bevacqua/dragula/builds/78756490

**Comment by btecu** [comment]
You can see the function is called about 20 lines above (line 409):
```
    if (...) {
      scroll();
      o.scrolling = true;
    } else {
      stopScroll();
    }
```

So I don't know what Travis deal is.

**Comment by bevacqua** [comment]
Travis'es deal is that `window.scroll` is already a thing. So we should use some other name

**Comment by btecu** [comment]
Good catch! Fixed a few more styling issues.

**Comment by btecu** [comment]
Seems like this isn't necessary anymore...

**Pull request closed without merging**
