### PR TITLE
Add option for delay mirror

### PR DESCRIPTION
**Pull request by juanj**
Added the delay suggested at #190

### CODE REVIEW

**Comment by bevacqua** [comment]
Thanks but no thanks

**Comment by moldcraft** [comment]
@juanj How to test the changes [here](http://sourcebox.io/e5b9301c3d61f59b7a540af5a6f7e330/html) ?

Scroll down, replace 

```html
<script src="http://bevacqua.github.io/dragula/dist/dragula.js"></script>
```

with your version (with delay parameter), Save and give me the link here.

**Comment by juanj** [comment]
@moldcraft Here is the [link](http://sourcebox.io/a5c2efe598885b297935ae81885679a5/html)
The code adds the new option "mirrorDelay".
To use it
```javascript
dragula(containers, { mirrorDelay:200 } );
```
The delay is in milliseconds

**Comment by moldcraft** [comment]
[Here](http://sourcebox.io/c3a513956f2bbcb098a1094778d46172/html) is the working version

*P.S. Use http://rawgit.com to convert Github url to url usable in `<script>` and `<link rel="stylesheet">`*

But it has some problems:

* Some times the delay is not working, the element is moved instantly
* There is a [glitch while moving](https://vid.me/ITCI)

----

Can you make a pull request more tested and to pass Travis validation?

**Comment by moldcraft** [comment]
*I finished migration from jquery draggable+sortable to dragula*

@juanj The glitch is very bad https://vid.me/TlbV with it the delay feature is useless. So I will use original dragula.js at the moment

Can you please fix the glitch and I will pay you again on bountysource?

**Comment by moldcraft** [comment]
We found a way to [change a jQuery sortable instance method](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/master/includes/option-types/builder/static/js/builder.js#L656-L708) to delay the placeholder position update, it works more stable than this fix.

**Pull request closed without merging**
