### PR TITLE
Added isCopy

### PR DESCRIPTION
**Pull request by beatfreaker**
Added isCopy function and replaced all o.copy with it to allow user
defined copy condition check.
PR for [#119](https://github.com/bevacqua/dragula/issues/119) issue.

### CODE REVIEW

**Comment by beatfreaker** [comment]
please check and let me know if need any modification.

**Comment by bevacqua** [comment]
What if the `copy` function returns `true` for the source container and `false` for the target? What if it returns `false` for the source and `true` for the target?

This is my major concern about this feature

**Comment by guillaumepiot** [comment]
Yes that is a concern I agree. In my case, I only need to know depending on the element being dragged itself. I'm my current pull request, you can decide if it is copy based on the container, but not based on the target.

Personally, I think the copy should only happen when starting the drag, letting the original element showing fully in its original position, while dragging a copied shadow of it.

A copy on target, would make the original element flicker back in position depending whether the target accepted it as a copy or a move, not knowing at the start of the drag whether to leave it it there or move it out.

**Comment by bevacqua** [comment]
We need to either refactor the whole thing or figure out if the feature is with merits without the context of a container. I think allowing it to be based on the target container doesn't add much value. Do you think there's a use case for that? Otherwise we could just do `(el, source)` for arguments.

**Comment by guillaumepiot** [comment]
The only use case I can think of where the container will be required is when we would drag an element that will act as "template" element, into another container.

Those "template" elements would be copied from their "pool" container to populate other containers.

Let's say I build a recipe, I may drag and copy "ingredients" from a list into a recipe container. Having said that, the "ingredient" could be marked as copiable based in the element itself (no need to mark the container).

I would even argue that `(el)` would be sufficient for arguments, using an attribute to mark them as copiable (eg: `data-copy="true"`).

The project I'm working on in which I have integrated dragula (beta.cyanapp.com), allow the drag or copy of events within a schedule calendar, so the `el` argument is sufficient for my specific case.

**Comment by bevacqua** [comment]
I'm leaning towards agreement that consumers should work their way around if they need to allow copying based on target, it's just unnatural and really complicates the code. Let's omit that one. Let's just do `(el, container)` where `container` is the source container.

**Comment by bevacqua** [comment]
Code seems to match what we discussed. Let's add documentation and we can merge this in.

**Comment by beatfreaker** [comment]
by documentation you mean to update just readme.markdown or add document the code too??

**Comment by bevacqua** [comment]
Just the readme! :)

**Comment by beatfreaker** [comment]
Added documentation for this change in readme and committed to same branch please check.

**Comment by bevacqua** [comment]
Okay so I've added some tests to the project. It would be cool if we wrote tests for all the things we add, so over time we keep on improving the test suite. Do you think you could write some tests to verify that `copy` accepts both a `boolean` and `function`? _(and that the `function` gets called)_

Thanks

**Comment by bevacqua** [comment]
Made a bunch of inline comments about the `readme` documentation changes, please take a look. Thanks!

**Comment by beatfreaker** [comment]
Updated the documentation according to you inline comments please check.

**Comment by beatfreaker** [comment]
Updated the doc .... and what's with this Travis CI why it is giving "All checks have failed error" ?

**Comment by bevacqua** [comment]
If you click on details it'll let you in on why it's failing. It says:

```
dragula.js
  line 514  col 14  'o' is not defined.
  line 515  col 12  'o' is not defined.
  line 517  col 10  'o' is not defined.
  line 517  col 17  'el' is not defined.
```

**Comment by beatfreaker** [comment]
Done .... please check now.

**Comment by beatfreaker** [comment]
@bevacqua can you please guide me with writing tests ? have no idea about it just give me a head start and i will write the tests to verify `copy` accepts both `boolean` and `function`.

**Comment by beatfreaker** [comment]
@bevacqua any update??

**Comment by bevacqua** [comment]
I think this is a good example of a test like what you have to write: https://github.com/benib/dragula/blob/config-mirror-parent/test/drag.js#L176-L193

**Comment by beatfreaker** [comment]
@bevacqua can you please review the following test :
```js
test('when dragging, check for copy option', function (t) {
  var mirrorContainer = document.createElement('div');
  var div = document.createElement('div');
  var item = document.createElement('div');
  item.className = "copyable";
  var drake = dragula([div], {
    copy: checkCondition
  });
  item.innerHTML = '<em>the force is <strong>with this one</strong></em>';
  div.appendChild(item);
  document.body.appendChild(div);
  events.raise(item, 'mousedown', { which: 0 });
  t.plan(1);
  t.end();
  function checkCondition (el, container) {
    t.equal(el.className, 'copyable', 'dragged element classname is copyable');
    return true;
  }
});
```

**Comment by bevacqua** [comment]
Looks fine, stick to single quotes. We probably need a couple more where we check the method is being used in the various places where `copy` would be used. Could you add those too?

**Comment by beatfreaker** [comment]
can you please tell me what sort of other test cases i can write?

**Comment by beatfreaker** [comment]
@bevacqua can you tell about any other scenario in which copy will be used and you want me to write test case about it.

**Comment by bevacqua** [comment]
I meant tests covering the different places in the source code where `isCopy()` is being called

**Comment by beatfreaker** [comment]
Please close this PR and check out this new PR [#160](https://github.com/bevacqua/dragula/pull/160)

**Pull request closed without merging**
