### PR TITLE
Added copyFunc for custom copy handler

### PR DESCRIPTION
**Pull request by tazdij**
I needed to override the copy functionality to allow for modifying copied elements or create completely different elements instead. just return an element from the function. Example:
{
    copy: true,
    copyFunc: function(el, source) { return el.cloneNode(true); }
}

### CODE REVIEW

**Comment by tazdij** [comment]
Does anyone have any desire to have this functionality added into the library. I needed for a project I am working on, so I added it to my fork. I thought that I should create a pull request so that you can see the added feature and determine if it should be merged back into the project.

**Comment by L1h3r** [comment]
+1 this would be nice to have

**Comment by texel** [comment]
This would be great.

**Comment by bevacqua** [comment]
How is this any better than using the `cloned` event?

**Comment by tazdij** [comment]
I didn't even try to use the cloned event queue, nor did I realize I could use that. However, I think I like my copy function to be included in the config object, and not as a separate function listening to a queue. Like I said, I just added the pull request to see if you liked the change. If you don't think it is worth merging, I am perfectly fine with it.

Thanks,

**Comment by bevacqua** [comment]
I was just wondering if there's something you can do with the option that you couldn't do with the event

**Comment by tazdij** [comment]
You're welcome, if I make anymore changes to my fork, I will submit pull requests for the features, so you can see them and determine if you would like them in the main repo. Also, great job on dragula, I am really liking it so far.

**Pull request closed without merging**
