### PR TITLE
Add axis option to specify axis restriction

### PR DESCRIPTION
**Pull request by nguyenj**
This restricts the element being dragged to the specify axis via options.

### CODE REVIEW

**Comment by andreiglingeanu** [comment]
Really looking forward into getting this merged as soon as possible!

**Comment by balazsnemeth** [comment]
@bevacqua , @gnujeremie , @jimf ? What do you think, can this be merged?

**Comment by andreiglingeanu** [comment]
I'm using this pull request in a fork of `dragula` for quite some time already. It is pretty solid and deserves a merge.

**Comment by alsoicode** [comment]
+1 I also need this

**Comment by n1ru4l** [comment]
+1

**Comment by Xykcya** [comment]
+1

**Comment by fredbouchard** [comment]
+1

**Comment by xevinbox** [comment]
+1

**Comment by UlisesCabrera** [comment]
+1

**Comment by nguyenj** [comment]
Hate to say it guys; but I believe @bevacqua has abandon this project. There hasn't been any **real** updates to the library September 2016 (a13d7db9e698fa9bc866855a5556ca5fb61f2bc2).

**Comment by bevacqua** [comment]
@nguyenj Haven't abandoned it, just haven't personally needed updates to it lately & not a lot of free time to sink into OSS.

**Comment by n1ru4l** [comment]
@bevacqua Would you consider adding additional maintainers?

**Comment by nguyenj** [comment]
@bevacqua okay great! And to @n1ru4l point; have you considered adding maintainers?

**Comment by d-steinberg** [comment]
Still waiting on this - very worthy PR

**Comment by InigoWD** [comment]
@nguyenj How do I get this to work? I am using angular 2 cli, have installed with:

`npm install git://github.com/nguyenj/dragula.git`

and am setting options:

`  getDragOps(){
    return {
      direction: 'vertical',
      axis: 'y',
      mirrorContainer: document.getElementById('cat-tree-builder'),
      moves: function (el, container, handle) {
        return handle.classList.contains('handle');
      },
    }
  }`

But it's not working- dragging is not restricted...

**Comment by romain10009** [comment]
+1  would love it! very needed

**Comment by nguyenj** [comment]
Might be worth looking at https://github.com/Shopify/draggable

**Comment by nguyenj** [comment]
Closing this as this project is DEAD.

**Comment by jaschaio** [comment]
@nguyenj do you mean dragula is not longer maintained and therefore draggable is a better option? This is the first time I've heared that dragula is DEAD so would be great to get more info on this.

**Comment by andreiglingeanu** [comment]
@jaschaio probably both of them

**Pull request closed without merging**
