### PR TITLE
handle standard pointer events

### PR DESCRIPTION
**Pull request by gleborgne**

### CODE REVIEW

**Comment by bevacqua** [comment]
What does this fix?

**Comment by gleborgne** [comment]
Weird behavior on Windows 10 Phone version

**Comment by gleborgne** [comment]
And this fix will use pointers in compatible browsers (no MS prefixes)

**Comment by bevacqua** [comment]
Fine, I'll use the code but I'll put in another commit so that it adheres to the code style in `dragula`

**Comment by gleborgne** [comment]
Thanks

**Pull request closed without merging**
