### PR TITLE
Cursor now looks as if it is picking up the object and moving it.

### PR DESCRIPTION
**Pull request by Andexus**

### CODE REVIEW

**Comment by bevacqua** [comment]
Shouldn't this be up to the lib consumer?

**Comment by Andexus** [comment]
Yes, and they can totally change it. I'd think it would make more sense to put it here due to the fact many people will try and add it. I think having the cursor show it is grabbing and moving the object is quite convenient.

**Comment by bevacqua** [comment]
Fair enough :)

**Comment by bevacqua** [comment]
Deployed to `gh-pages`

**Pull request merged**
