### PR TITLE
Add option 'ignoreItemOffsetOnMirrorPosition'

### PR DESCRIPTION
**Pull request by Metroslim**
When the user drag an item -> the mirror DOM item get positionned relative to the mouse position with OR without correcting it with its offsets.

### CODE REVIEW

**Comment by dcantatore** [comment]
@Metroslim Can you explain this further? Is this in reference to an issue?

**Comment by Metroslim** [comment]
@dcantatore I didn't look at the issues before doing this PR but it seems that it can answer the issue https://github.com/bevacqua/dragula/issues/616.

If the option is set to true then the mirror DOM will be position on the pointer. To be precise, the left top corner of the mirror DOM will be just under the pointer. To fullfill the need of the related issue you just have to add transform: translate(-50%) to the .gu-mirror css.

If you want I can take some screen capture to demonstrate.

**Comment by dcantatore** [comment]
@Metroslim -  Screen capture would be great. Can you add the css change as well as the information to the readme?

**Comment by Metroslim** [comment]
Hey, screen capture wasn't that easy (confidential project) but I just push updates on Readme and Examples with the information relative to this new option. I'm not an native english speaker so maybe you will find better way to explain the feature. BTW, I'm using ng2-dragula and if you merge this PR you will have to update the @types so that the DragulaOption will be in sync. Thank for your work !

**Comment by Metroslim** [comment]
Hi there, I haven't heard from you since two weeks. Did you look at my new commit that include a new section in the example to demonstrate what this new option offer ?
(BTW I may be using swivel for handling communication between pages and service worker so thanks again for the gret work !)

**Pull request closed without merging**
