### PR TITLE
Adding Dragula Logo :ok_hand:

### PR DESCRIPTION
**Pull request by debone**
dragula-final-branco

### CODE REVIEW

**Comment by bevacqua** [comment]
Awesome stuff. I've made it into a favicon and added it to the demo page :dancer:

**Comment by debone** [comment]
:dancer:

**Comment by voidale** [comment]
@debone did you create this logo? It's freaking amazing. Are you a designer?

**Comment by bevacqua** [comment]
Yeah. He's freaking amazing, too! :rocket

**Comment by voidale** [comment]
@bevacqua yeah! I also need a rockstar logo which is unique and simple just like Dragula =) @debone Victor if it's possible you can contact me my email newgene11@gmail.com (Your github info is outdated). Thanks!

**Pull request merged**
